### ISSUE TITLE
Выборочное подключение скриптов

### ISSUE THREAD

**Issue by Taatshi** [Joomline/JsCssManipulate#2]
Добавить к каждому подключаемому скрипту и css файлу функцию выбора страниц для подключения, например, по пунктам меню как у модулей.

Было бы неплохо в итоге)

**Comment by Arkadiy-Sedelnikov** [comment]
Я уже про это думал, но пока не знаю как лучше сделать. По моему более тонко можно будет сделать не пунктами мею а параметрами реквеста. Просто строка для ввода параметров, а там прописать необходимые параметры и их значения.

**Comment by Taatshi** [comment]
Реквестом разрабы тебя расцелуют, а вот простые юзвери взвоют) Может, сделать режим пользовательский попроще и режим разраба - покруче? Переключателем.

**Comment by Arkadiy-Sedelnikov** [comment]
Ты же знаешь, я для чайников делать не люблю :)

**Comment by Arkadiy-Sedelnikov** [comment]
add052ffbdfc9dbecfb566462f3af5b41eb11e86
