### ISSUE TITLE
Не обрабатываются стили и скрипты от шаблона протостар

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JsCssManipulate#3]
Почему то плагин не перехватывает css и js от стандартного шаблона Joomla.

Формат вызова вот такой:
http://demo3.joomline.ru/templates/protostar/css/template.css?54c52778af287839b0198ec5d327ef49

**Comment by Arkadiy-Sedelnikov** [comment]
Его так и надо вписывать в строку пути, путь проверяется на точное соответствие. Если цифра после вопроса изменится (я не знаю по какому принципу она генерируется), то файл снова не будет перехватываться.

**Comment by zikkuratvk** [comment]
а может быть какое нибудь значени типя * добавить??

**Comment by Arkadiy-Sedelnikov** [comment]
Вместо чего его предполагется использовать?

**Comment by proweb** [comment]
все перехватывается если указывать без параметров.
Тестирую ща на J 3.7
![_086](https://cloud.githubusercontent.com/assets/680073/26116587/5645ce92-3a6c-11e7-97ab-d1fe4f0aae6e.png)

Но хотелось бы просто указывать имена файлов, а не полный путь(спорно конечно)

И еще одна беспокоящая вещь - можно какую то опцию (радиобаттон) чтоб вырезать вот это:
```
<script>
jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});
</script>
```
А то реально подбешивает эта врезка по дефолту.

**Comment by Arkadiy-Sedelnikov** [comment]
1. Имена файлов без путей использовать нельзя, есть много одноименных скриптов/стилей расположенных в разных папках.
2. С этим надо подумать. Вычищать скрипты иногда надо, но как это сделать наиболее универсально - вопрос. Самый простой для меня, самый мощный, но самый сложный для пользователей вариант - просто сделать поле для регулярки, которая будет вырезать ненужное из скрипта.

**Comment by Arkadiy-Sedelnikov** [comment]
А по началу топика - в плагине есть отладка, в которой показаны все пути к файлам скриптов и стилей именно в том варианте, в котором их надо вставлять в поля плагина, отгда они будут обрабатываться.

**Comment by Arkadiy-Sedelnikov** [comment]
Сделал вырезку из скрипта регулярками https://github.com/Joomline/JsCssManipulate/releases/tag/1.2.0
Регулярка для вырезки 
`<script>
jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});
</script>`
будет такая:
`/jQuery\(window\).on\('load',  function\(\) \{\n(\s\s+)new JCaption\('img.caption'\);\n(\s\s+)\}\);/s`
