### ISSUE TITLE
LESS и SCSS компилятор

### ISSUE THREAD

**Issue by viocassel** [Joomline/JsCssManipulate#4]
Отличный плагин!

Было бы очень хорошо, если бы добавили функционал компиляции LESS файлов используя, к примеру, библиотеку [Less.php](https://github.com/oyejorge/less.php/).
Например, компилировать файл от корня шаблона `less/template.less` в файл `css/template.css`.

Подобный функционал есть в плагине [plg_system_less](https://github.com/viocassel/plg_system_less).
![photo_2017-05-04_15-09-22](https://cloud.githubusercontent.com/assets/3341562/25704363/c5aabe58-30e1-11e7-8842-7fac13d5f99e.jpg)

Если получится добавить еще и функционал компиляции SCSS файлов, будет еще лучше 😉

**Comment by zikkuratvk** [comment]
я бы тогда указывал не конкретные файлы, а папки, так как, как может быть и несколько less файлов в одной папке.

**Comment by viocassel** [comment]
Ну не совсем подходящее. Что если тебе не все файлы из папки нужно компилировать или еще что-то...? А в основной файл который компилируем, можно подтягивать другие файлы импортом.

Но если мы хотим скомпилировать несколько файлов `.less` в несколько файлов `.css` раздельно, то нужно тогда сделать так, чтобы можно было указывать какой файл куда компилировать. 

Например
`less/test1.less -> css/test1.css`
`less/abc/test2.less -> css/abc/test2.css`
`less/xyz/test3.less -> css/xyz/test3.css`

Ну а потом все это объединять и пресовать CSS компрессором.

**Comment by zikkuratvk** [comment]
ммм... ну тогда размножаемое поле тут больше всего подойдет.

**Comment by Arkadiy-Sedelnikov** [comment]
Сделаю вторую вкладку с полями как в первой.

**Comment by proweb** [comment]
@viocassel прав @zikkuratvk 
работаю и с less и с scss - по практике компилится один файл, в который импортируются остальные.

**Comment by viocassel** [comment]
@proweb я тоже думаю что опция с множественным компилированием раздельных файлов будет редко использоваться. Обычно компилировать будут один общий файл куда подтянут остальные файлы. Но, как опция, я думаю, лишней не будет. 😉

**Comment by Arkadiy-Sedelnikov** [comment]
43f9ad1231350e4266722194388566d405032cde
Сделал компиляцию Less/Sass, для компиляции надо указать путь к исходнику от корня сайта и путь к целевому css. При компиляции css не аттачатся в head, т.е. они должны быть приаттачены в шаблоне или расширениях. Если надо окмпилировать несколько файорв и хочется их слить в один файл, то сначала компиляция по отдельности, потом все операции с полученными css файлами как обычно.
Компиляция не происходит если целевой css есть и время его изменения не позже времени изменения исходника.
Компилировать из Less или Sass выбирается по расширению файлов. *.less и *.scss. Если есть другие расширения, прошу сообщить.

**Comment by AlekVolsk** [comment]
файлы .scss также могут иметь расширение .sass

**Comment by Arkadiy-Sedelnikov** [comment]
Ок, добавил.
